spring:
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t

