server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: users-service
            uri: lb://USERS-SERVICE
            predicates:
              - Path=/user/**
          - id: vehicle-service
            uri: lb://VEHICLE-SERVICE
            predicates:
              - Path=/vehicle/**

