server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
        routes:
          - id: users-service
            uri: http://localhost:8091
            predicates:
              - Path=/user/**
          - id: vehicle-service
            uri: lb://vehicle-service/
            predicates:
              - Path=/vehicle/**

