server:
  port: 8094

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.formatiom.kafka.notification.notificationservice.impl.UserPlacedEvent
  application:
    name: notification-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost
