server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.fomation.micromongo.persistence.impl.UserPlacedEvent
  application:
    name: users-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost



