server:
  port: 8095


spring:
  application:
    name: vehicle-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test




