spring:
  main:
    web-application-type: reactive
  config:
    import: configserver:http://localhost:8080
  application:
    name: vehicle-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t






